spring.application.name=emploidutemps

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.kzyerqmbsikfucyryaot&password=Azertyuiopw@10001
spring.datasource.username=postgres.kzyerqmbsikfucyryaot
spring.datasource.password=Azertyuiopw@10001
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080